@startuml
!include <archimate/Archimate>
Motivation_Goal(goal1,"Seamless, secure, and tailored digital experiences")

Motivation_Requirement(requirement1,"Unified banking app")
Motivation_Requirement(requirement2,"Robust security measures")

Motivation_Outcome(outcome1,"Increased user engagement")
Motivation_Outcome(outcome2,"Higher rate of loan applications through digital channels")
Motivation_Outcome(outcome3,"Improved NPS scores for digital services")


Rel_Realization(requirement1,goal1,Realization)
Rel_Realization(requirement2,goal1,Realization)
Rel_Influence(outcome1,goal1,Influence)
Rel_Influence(outcome2,goal1,Influence)
Rel_Influence(outcome3,goal1,Influence)
Application_Component(appcomponent1,"Unified banking app")

Application_Function(appfunction1,"Personalized insights")
Application_Function(appfunction2,"Machine learning-driven product recommendations")
Application_Function(appfunction3,"Biometric authentication")
Application_Function(appfunction4,"Fraud detection")


Rel_Assignment(appfunction1,appcomponent1,Assignment)
Rel_Assignment(appfunction2,appcomponent1,Assignment)
Rel_Assignment(appfunction3,appcomponent1,Assignment)
Rel_Assignment(appfunction4,appcomponent1,Assignment)
@enduml